name: test2

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run functional_test1
      run: |
        output=$(node func_test1.js)
        # Capture the exit code of the previous command
        exit_code=$output

        # Check the exit code to determine if there was an error
        if [ $exit_code -ne 0 ]; then
          echo "Error: The Node.js script failed with exit code $exit_code"
          # You can add more error-handling actions here if needed
          exit 1  # Exit the workflow with an error code
        fi
        
