name: Print Text from hellome.html

on:
  push:
    branches:
      - main
jobs:
  print-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print text from file.txt
      run: cat hellomex.html
